-- AlterTable
ALTER TABLE `application` ADD COLUMN `type` ENUM('APPLICATION', 'OFFER') NOT NULL DEFAULT 'APPLICATION',
    MODIFY `status` ENUM('PENDING', 'ACCEPTED', 'REJECTED', 'COMPLETED', 'CANCELLED') NOT NULL DEFAULT 'PENDING',
    MODIFY `contactName` VARCHAR(191) NULL,
    MODIFY `contactPhone` VARCHAR(191) NULL,
    MODIFY `cvIds` JSON NULL;
